lgvd_config:
  num_steps: 100
  lr: 5e-5
  tau: 0.01
  lr_min_ratio: 0.01


operator:
  name: inpainting
  mask_type: box  # box
  mask_len_range: [128, 129]  # for box
  # mask_prob_range: !!python/tuple [ 0.3, 0.7 ]  # for random
  resolution: 256
  sigma: 0.05
